# Generated by Django 3.0 on 2020-01-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=20)),
                ('ldaps', models.BooleanField()),
                ('cert_content', models.TextField(blank=True, null=True)),
                ('bind_dn', models.CharField(max_length=255)),
                ('bind_password', models.CharField(max_length=255)),
            ],
        ),
    ]
