# Generated by Django 3.0 on 2020-01-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ldap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapconfig',
            name='access_groups',
            field=models.TextField(default='polo'),
            preserve_default=False,
        ),
    ]
